"""Add correct column for answer

Revision ID: fae5a1f46b98
Revises: 1bbe27eee12c
Create Date: 2021-07-28 23:08:27.939357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fae5a1f46b98'
down_revision = '1bbe27eee12c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'correct')
    # ### end Alembic commands ###
